
@baseUri = http://localhost:8182/api

### Index
GET {{baseUri}}/orders HTTP/1.1
content-type: application/json

### Store
POST {{baseUri}}/orders HTTP/1.1
content-type: application/json

{
    "customer_id": 10,
    "total": 20,
    "status": "cancelled",
    "paid_at": "2026-06-10 11:30:45"
}

### Show
GET {{baseUri}}/orders/10 HTTP/1.1
content-type: application/json

### Update
PUT {{baseUri}}/orders/12 HTTP/1.1
content-type: application/json

{
    "customer_id": 10,
    "total": 20,
    "status": "cancelled",
    "paid_at": "2026-06-10 11:30:45"
}

### Delete
DELETE  {{baseUri}}/orders/2 HTTP/1.1
content-type: application/json
