
@baseUri = http://localhost:8182/api

### Index
GET {{baseUri}}/reviews HTTP/1.1
content-type: application/json

### Store
POST {{baseUri}}/reviews HTTP/1.1
content-type: application/json

{
    "product_id": 70,
    "customer_id": 18,
    "rating": 2,
    "comment": "Officiis et rem omnis vero occaecati magni. Facere exercitationem facilis quisquam. Numquam aspernatur molestias sunt voluptatem."
}

### Show
GET {{baseUri}}/reviews/16 HTTP/1.1
content-type: application/json

### Update
PUT {{baseUri}}/reviews/16 HTTP/1.1
content-type: application/json

{
    "rating": 4,
    "comment": "Review atualizado"
}

### Delete
DELETE  {{baseUri}}/reviews/18 HTTP/1.1
content-type: application/json
